In [1]:
import numpy as np
from itertools import permutations

import gymnasium as gym
from gridworld.envs import GridWorldEnv, SiblingGridWorldEnv
from gymnasium.wrappers import FlattenObservation
from gridworld.wrappers import RelativePosition, InvertedReward
from gymnasium.envs.registration import register

<frozen importlib._bootstrap>:241: RuntimeWarning: Your system is avx2 capable but pygame was not built with support for it. The performance of some of your blits could be adversely affected. Consider enabling compile time detection with environment variables like PYGAME_DETECT_AVX2=1 if you are compiling without cross compilation.


In [2]:
def sibling():
    env = SiblingGridWorldEnv()
#     env = RelativePositionenv)
    return env

register(
    id='SiblingGridWorld-v0',
    entry_point=sibling,
    max_episode_steps=300,
)

In [3]:
env = gym.make('SiblingGridWorld-v0')
print(env.reset())
# wrapped_env = InvertedReward(env)
# print(wrapped_env.reset())

(array([ 4,  0, 18]), {'distance': 4.0})


In [4]:
env = env.unwrapped

In [5]:
# env.render_mode = 'human'
env.reset()

(array([ 2,  2, 14]), {'distance': 4.0})

In [12]:
obs, rew, done, trunc, info = env.step(np.array([3, 0]))
obs, rew, done, trunc, info

({'agent': (array([2, 4]), array([0])), 'target': array([4, 4])},
 -6,
 False,
 False,
 {'distance': 2.0})

In [19]:
env.close()

In [10]:
env._world_belief

array(23)

In [8]:
env.worlds[env._world_belief[0]]

IndexError: invalid index to scalar variable.

In [6]:
true_map = np.array(
    [[1, 0], [0, -1], [-1, 0], [0, 1]]
)

In [7]:
np.array(list(permutations(true_map)))[1]

array([[ 1,  0],
       [ 0, -1],
       [ 0,  1],
       [-1,  0]])

In [8]:
d = dict(zip(range(24), np.array(list(permutations(true_map)))))

In [9]:
np.array_equal(true_map, d[0])

True

In [10]:
rng = np.random.default_rng()
rng.integers(0, 5, size=2, dtype=int)

array([1, 2])